version: '3.8'

services:
  bot:
    build: .
    container_name: bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080" 